[relaychain]
default_command = "./bin-stable2412/polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9955

[[parachains]]
id = 1000

[parachains.collator]
name = "charlie"
ws_port = 9988
command = "./target/release/parachain-template-node"
